version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"