name: Run Python Lint Checks

on:
  push:
    branches:
      - main
    paths:
      - 'streamget/**'
      - 'requirements.txt'
      - '.ruff.toml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'streamget/**'
      - 'requirements.txt'
      - '.ruff.toml'

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff

      - name: Run ruff lint check
        run: ruff check streamget --config .ruff.toml
        working-directory: .
